spring:
  application:
    name: helloworld
  jwt:
    accessTokenExpiry: 7200 #2h
    refreshTokenExpiry: 86400 #7d
    secret: ${JWT_SECRET}
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}